### ISSUE TITLE
Question on data loader mask process

### ISSUE THREAD

**Issue by chorongi** [epic-kitchens/VISOR-VOS#2]
https://github.com/epic-kitchens/VISOR-VOS/blob/f223ec239aae5e2f3ecc7e8d868ee770cbbaab74/dataset/visor.py#L73

I had a question on what this function does. 
It seems like it has no effect on the masks? What is the number 11 for? Why if f==0?

Thank you in advance.

**Comment by chorongi** [comment]
I also have a question how evaluation works. 
I looked at the masks, and I found that color of objects are inconsistent over sequences (even from same video)
Are we expected to eval per-seq?

**Comment by AhmadDarKhalil** [comment]
Thank you for reachin out,
Regarding `mask_process` function, the function mainly prepare the sampled masks for training, i.e. we usually select 3 images during training and this consider the first one as the reference frame and filter out any other objects in the following 2 images.  `if f==0` is used  indicates the first frame (i.e. reference frame). For number 11, it should be a number that is larger than the number of objects in the current PNG mask, I updated the code to replace 11 with the maximum code in the PNG image for more redable code, thanks for the note. I put comments in the function so hopefully now is easier to follow.

The `mask_process` function function is also useful when you want to set  MAX_OBJECT_NUM_PER_SAMPLE variable, if you put that to 5 for example, then if the number of objects in the reference frame is more than 5, it randomly sample 5 objects (this might be used to have easier training examples rather than tracking all objects). 

For evaluation, we evalaute per sequence, i.e. the first frame of the sqeuence is the reference frame (given) and you have to track it's objects for all the remaining frames of that sequence.
Please let me know if you have any further quesitons

**Comment by chorongi** [comment]
I also found annotation for P01_107_seq_00013/P01_107_frame_0000004919.jpg
is missing for the dataset.

**Comment by AhmadDarKhalil** [comment]
I've checked the code, it's not actually missing annotation, this case happends when all the object masks have been deleted after filtering them according the first frame, so we ignore this frame as we evaluate on the frames with at least one object mask. But keeping the RGB image is confusing, so I updated the ```utils/vis.py ``` code to remove those RGB images (line 69-71).

Happy to help in any further questions or concerns.

**Comment by chorongi** [comment]
Thank you for the kind explanation. I'm trying to understand the dataset/task before i do more research. So if you see the first sequence, you can see that the only object that was annotated in the first frame is the door. (red) but we see new objects interacting with the hand show up in the second frame. I got confused how the dataset was labeled "according to the first frame"? Thanks in advance. 

![image](https://user-images.githubusercontent.com/35532722/227661454-049638ea-4028-4176-98c6-d881ae96f3ec.png)

**Comment by AhmadDarKhalil** [comment]
Thank you for getting in touch again. I apologize if there was any confusion earlier. To ensure that the dataset is consistent with other datasets such as DAVIS and YT-VOS and suitable for semi-supervised VOS, we have made the following decisions:
Train set: We do not filter out any objects, meaning there is no need to remove objects that do not appear in the first frame. Instead, during training, methods will randomly N samples i.e. three frames and filter them out according to the first frame of selected ones. The example you've included in part of the Train set so it's expected to see new objects in the subsequent frames.

Val set: We do filter out any objects that do not appear in the first frame. This is because we're using this split for evaluation, where we propagate the objects in the first frame -only- until the end of the sequence. We only want to keep the objects that appear in the first frame as ground truth, as without this, the model will be penalized for new objects that appear in subsequent frames. Other datasets like DAVIS designed only for the VOS/VIS challange so they originally annotated objects in the first frame while we have more diverse benchmarks so we select the subset of frames that relevent to this benchmark.

I hope that clearify the confusion, please don't hesitate to let me know about any further concerns.

**Comment by chorongi** [comment]
_Instead, during training, methods will randomly N samples i.e. three frames and filter them out according to the first frame of selected ones._

I'm still confused how the train set is generated from your comment above. What do you mean by "filter out according to first frame?" What kind of filtering process are you doing for train? (Would be great  if you provide an example... e.g. say first frame1 has obj 1,2,3 and frame 2 has obj 2,3,4, frame 3 has obj 1,3,5)

Apologies for not understanding well based on your comments..

**Comment by dimadamen** [comment]
We have provided the code so you should be able to go through it step by step and understand our explanation of what is loaded and how the evaluation takes place.
We are sorry but we not able to provide commentary/explanations for our published code. This is based on prior works on VOS so prior understanding might be required. 
We publish datasets and code voluntarily and our research time is thus restricted. These GitHub issues should be restricted to actual issues in running the code or replicating results.
